apiVersion: apps/v1
kind: Deployment
metadata:
  name: epm-dep-api
  labels:
    app: epm-dep-api
    env: prod
    owner: RomanGorokhovsky
spec:
  #replicas: 2
  selector:
    matchLabels:
      project: Epam
  template:
    metadata:
      labels:
        project: Epam
    spec:
      containers:
        - name: api
          image: madmongoose/api:latest
          ports:
            - containerPort: 5000

---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: epm-dep-api-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v2beta1v1
    kind: Deployment
    name: epm-dep-api
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 70
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 80
